// AUTO-GENERATED from data/trade_catalog.json by scripts/build_data_jsx.py — do not edit by hand.
// Non-destructive overlay: replaces STORE_DATA.products with the real 2026-03 trade catalog
// (USD, $/lb, format variants, availability) and switches currency to USD.
(function () {
  window.STORE_CURRENCY = "USD";
  const products = [
  {
    "id": "asiago-fresco-dop",
    "name": "Asiago Fresco DOP",
    "range": "Asiago",
    "price": 5.83,
    "priceMax": 6.2,
    "delivered": 6.13,
    "deliveredMax": 6.5,
    "unit": "lb",
    "multi": true,
    "image": "02005",
    "caseLb": 30.0,
    "caseLabel": "Whole Wheel, 28-30 lbs",
    "wholesale": 5.83,
    "weight": "3 formats · 15–30 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #064E22)",
    "badge": "PDO",
    "blurb": "Aged 30-40 days. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged 30-40 days",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": true,
    "formats": [
      {
        "code": "02005",
        "packing": "Whole Wheel, 28-30 lbs",
        "piecesPerCase": 1,
        "netLb": 30.0,
        "grossLb": 32.0,
        "palletTiHi": "6 x 8",
        "casesPerPallet": 48,
        "shelfDays": 360,
        "pickupLb": 5.83,
        "deliveryLb": 6.13
      },
      {
        "code": "02073",
        "packing": "1/4 Wheel, vacuum packed",
        "piecesPerCase": 1,
        "netLb": 15.0,
        "grossLb": 16.0,
        "palletTiHi": "12 x 8",
        "casesPerPallet": 96,
        "shelfDays": 240,
        "pickupLb": 6.01,
        "deliveryLb": 6.31
      },
      {
        "code": "02302",
        "packing": "SQUARE SHAPE FOR SLICING",
        "piecesPerCase": 3,
        "netLb": 28.0,
        "grossLb": 29.0,
        "palletTiHi": "6 x 12",
        "casesPerPallet": 72,
        "shelfDays": 240,
        "pickupLb": 6.2,
        "deliveryLb": 6.5
      }
    ]
  },
  {
    "id": "asiago-stagionato-dop",
    "name": "Asiago Stagionato DOP",
    "range": "Asiago",
    "price": 7.22,
    "priceMax": 7.42,
    "delivered": 7.52,
    "deliveredMax": 7.72,
    "unit": "lb",
    "multi": true,
    "image": "03023",
    "caseLb": 18.0,
    "caseLabel": "Whole Wheel, 17-19 lbs",
    "wholesale": 7.22,
    "weight": "2 formats · 4.4–18 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #064E22)",
    "badge": "PDO",
    "blurb": "Aged 5 months. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged 5 months",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "03023",
        "packing": "Whole Wheel, 17-19 lbs",
        "piecesPerCase": 1,
        "netLb": 18.0,
        "grossLb": 20.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 360,
        "pickupLb": 7.22,
        "deliveryLb": 7.52
      },
      {
        "code": "03010",
        "packing": "1/4 Wheel, vacuum packed",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 240,
        "pickupLb": 7.42,
        "deliveryLb": 7.72
      }
    ]
  },
  {
    "id": "asiago-vecchio-dop",
    "name": "Asiago Vecchio DOP",
    "range": "Asiago",
    "price": 7.89,
    "priceMax": 8.16,
    "delivered": 8.19,
    "deliveredMax": 8.46,
    "unit": "lb",
    "multi": true,
    "image": "03003",
    "caseLb": 17.0,
    "caseLabel": "Whole Wheel, 16-18 lbs",
    "wholesale": 7.89,
    "weight": "2 formats · 4.4–17 lb/case",
    "grad": "linear-gradient(145deg, #E3F0E1, #009640)",
    "badge": "PDO",
    "blurb": "Aged 9 months. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged 9 months",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": true,
    "formats": [
      {
        "code": "03003",
        "packing": "Whole Wheel, 16-18 lbs",
        "piecesPerCase": 1,
        "netLb": 17.0,
        "grossLb": 19.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 360,
        "pickupLb": 7.89,
        "deliveryLb": 8.19
      },
      {
        "code": "03014",
        "packing": "1/4 Wheel, vacuum packed",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 240,
        "pickupLb": 8.16,
        "deliveryLb": 8.46
      }
    ]
  },
  {
    "id": "asiago-fresco-della-montagna",
    "name": "Asiago Fresco della Montagna",
    "range": "Asiago",
    "price": 5.96,
    "priceMax": 5.96,
    "delivered": 6.26,
    "deliveredMax": 6.26,
    "unit": "lb",
    "multi": false,
    "image": "02206",
    "caseLb": 30.0,
    "caseLabel": "Whole Wheel, 28-30 lbs",
    "wholesale": 5.96,
    "weight": "1 format · 30 lb/case",
    "grad": "linear-gradient(145deg, #FFFBDC, #70C883)",
    "badge": "Mountain",
    "blurb": "Aged 60-70 days. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged 60-70 days",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "02206",
        "packing": "Whole Wheel, 28-30 lbs",
        "piecesPerCase": 1,
        "netLb": 30.0,
        "grossLb": 32.0,
        "palletTiHi": "6 x 8",
        "casesPerPallet": 48,
        "shelfDays": 240,
        "pickupLb": 5.96,
        "deliveryLb": 6.26
      }
    ]
  },
  {
    "id": "asiago-stagionato-della-montagna",
    "name": "Asiago Stagionato della Montagna",
    "range": "Asiago",
    "price": 7.62,
    "priceMax": 7.62,
    "delivered": 7.92,
    "deliveredMax": 7.92,
    "unit": "lb",
    "multi": false,
    "image": "03057",
    "caseLb": 18.0,
    "caseLabel": "Whole Wheel, 17-19 lbs",
    "wholesale": 7.62,
    "weight": "1 format · 18 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #009640)",
    "badge": "Mountain",
    "blurb": "Aged min 5 months. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged min 5 months",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "03057",
        "packing": "Whole Wheel, 17-19 lbs",
        "piecesPerCase": 1,
        "netLb": 18.0,
        "grossLb": 20.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 360,
        "pickupLb": 7.62,
        "deliveryLb": 7.92
      }
    ]
  },
  {
    "id": "montasio-cheese-dop",
    "name": "Montasio Cheese DOP",
    "range": "Alpine & Specialty",
    "price": 7.33,
    "priceMax": 7.49,
    "delivered": 7.63,
    "deliveredMax": 7.79,
    "unit": "lb",
    "multi": true,
    "image": "40020",
    "caseLb": 13.0,
    "caseLabel": "Whole Wheel, 16-18 lbs",
    "wholesale": 7.33,
    "weight": "2 formats · 13 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #141413)",
    "badge": "PDO",
    "blurb": "Aged 6 months. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged 6 months",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "40020",
        "packing": "Whole Wheel, 16-18 lbs",
        "piecesPerCase": 1,
        "netLb": 13.0,
        "grossLb": 14.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 360,
        "pickupLb": 7.33,
        "deliveryLb": 7.63
      },
      {
        "code": "40130",
        "packing": "1/4 Wheel, vacuum packed",
        "piecesPerCase": 4,
        "netLb": 13.0,
        "grossLb": 14.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 7.49,
        "deliveryLb": 7.79
      }
    ]
  },
  {
    "id": "vezzena-cheese",
    "name": "Vezzena Cheese",
    "range": "Alpine & Specialty",
    "price": 8.1,
    "priceMax": 8.22,
    "delivered": 8.4,
    "deliveredMax": 8.52,
    "unit": "lb",
    "multi": true,
    "image": "04181",
    "caseLb": 17.0,
    "caseLabel": "Whole Wheel, 16-18 lbs",
    "wholesale": 8.1,
    "weight": "2 formats · 4.4–17 lb/case",
    "grad": "linear-gradient(145deg, #064E22, #141413)",
    "badge": "Mountain",
    "blurb": "Aged 9 months. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged 9 months",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "04181",
        "packing": "Whole Wheel, 16-18 lbs",
        "piecesPerCase": 1,
        "netLb": 17.0,
        "grossLb": 19.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 360,
        "pickupLb": 8.1,
        "deliveryLb": 8.4
      },
      {
        "code": "04046",
        "packing": "1/4 Wheel, vacuum packed",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 240,
        "pickupLb": 8.22,
        "deliveryLb": 8.52
      }
    ]
  },
  {
    "id": "alpeggio-cheese",
    "name": "Alpeggio Cheese",
    "range": "Alpine & Specialty",
    "price": 8.07,
    "priceMax": 8.07,
    "delivered": 8.37,
    "deliveredMax": 8.37,
    "unit": "lb",
    "multi": false,
    "image": "20724",
    "caseLb": 13.0,
    "caseLabel": "Whole Wheel, 16-18 lbs",
    "wholesale": 8.07,
    "weight": "1 format · 13 lb/case",
    "grad": "linear-gradient(145deg, #FFFBDC, #064E22)",
    "badge": "Mountain",
    "blurb": "Aged min. 10 months. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged min. 10 months",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": true,
    "formats": [
      {
        "code": "20724",
        "packing": "Whole Wheel, 16-18 lbs",
        "piecesPerCase": 1,
        "netLb": 13.0,
        "grossLb": 14.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 8.07,
        "deliveryLb": 8.37
      }
    ]
  },
  {
    "id": "lagorai-cheese",
    "name": "Lagorai Cheese",
    "range": "Alpine & Specialty",
    "price": 6.29,
    "priceMax": 6.73,
    "delivered": 6.59,
    "deliveredMax": 7.03,
    "unit": "lb",
    "multi": true,
    "image": "04154",
    "caseLb": 30.0,
    "caseLabel": "Whole Wheel, 28-30 lbs",
    "wholesale": 6.29,
    "weight": "2 formats · 7–30 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #064E22)",
    "badge": "Mountain",
    "blurb": "Aged 60-70 days. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged 60-70 days",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "04154",
        "packing": "Whole Wheel, 28-30 lbs",
        "piecesPerCase": 1,
        "netLb": 30.0,
        "grossLb": 32.0,
        "palletTiHi": "6 x 8",
        "casesPerPallet": 48,
        "shelfDays": 340,
        "pickupLb": 6.29,
        "deliveryLb": 6.59
      },
      {
        "code": "04145",
        "packing": "1/4 Wheel, vacuum packed",
        "piecesPerCase": 1,
        "netLb": 7.0,
        "grossLb": 8.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 210,
        "pickupLb": 6.73,
        "deliveryLb": 7.03
      }
    ]
  },
  {
    "id": "fontal-trentinella",
    "name": "Fontal Trentinella",
    "range": "Alpine & Specialty",
    "price": 5.05,
    "priceMax": 6.73,
    "delivered": 5.35,
    "deliveredMax": 7.03,
    "unit": "lb",
    "multi": true,
    "image": "04067",
    "caseLb": 18.0,
    "caseLabel": "Whole Wheel, 28-30 lbs",
    "wholesale": 5.05,
    "weight": "3 formats · 4.4–18 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #064E22)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "04067",
        "packing": "Whole Wheel, 28-30 lbs",
        "piecesPerCase": 1,
        "netLb": 18.0,
        "grossLb": 20.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 6.64,
        "deliveryLb": 6.94
      },
      {
        "code": "04168",
        "packing": "1/4 Wheel, vacuum packed",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 180,
        "pickupLb": 6.73,
        "deliveryLb": 7.03
      },
      {
        "code": "20511",
        "packing": "FONTAL EU 1/4 Wheel, vacuum pack",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 5.05,
        "deliveryLb": 5.35
      }
    ]
  },
  {
    "id": "caciotta-basket-rind",
    "name": "Caciotta (Basket Rind)",
    "range": "Caciotta",
    "price": 5.9,
    "priceMax": 7.67,
    "delivered": 6.2,
    "deliveredMax": 7.97,
    "unit": "lb",
    "multi": true,
    "image": "20141",
    "caseLb": 6.0,
    "caseLabel": "PICCANTE (with red peppers) 6 lb",
    "wholesale": 5.9,
    "weight": "4 formats · 6 lb/case",
    "grad": "linear-gradient(145deg, #E3F0E1, #009640)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20141",
        "packing": "PICCANTE (with red peppers) 6 lb",
        "piecesPerCase": 1,
        "netLb": 6.0,
        "grossLb": 6.5,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 5.9,
        "deliveryLb": 6.2
      },
      {
        "code": "20142",
        "packing": "BLACK PEPPER (with black peppers) 6 lb",
        "piecesPerCase": 1,
        "netLb": 6.0,
        "grossLb": 6.5,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 5.98,
        "deliveryLb": 6.28
      },
      {
        "code": "20228",
        "packing": "HERBS (with aromatic herbs) - 6 lb",
        "piecesPerCase": 1,
        "netLb": 6.0,
        "grossLb": 6.5,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 5.98,
        "deliveryLb": 6.28
      },
      {
        "code": "20150",
        "packing": "TRUFFLE  (with black truffle)  6 lb",
        "piecesPerCase": 1,
        "netLb": 6.0,
        "grossLb": 6.5,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 7.67,
        "deliveryLb": 7.97
      }
    ]
  },
  {
    "id": "caciotta-basket-rind-small",
    "name": "Caciotta (Basket Rind, Small)",
    "range": "Caciotta",
    "price": 6.13,
    "priceMax": 7.94,
    "delivered": 6.43,
    "deliveredMax": 8.24,
    "unit": "lb",
    "multi": true,
    "image": "20144",
    "caseLb": 7.5,
    "caseLabel": "PICCANTE (with red peppers) 1,2 lbs",
    "wholesale": 6.13,
    "weight": "4 formats · 7.5 lb/case",
    "grad": "linear-gradient(145deg, #FFFBDC, #70C883)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20144",
        "packing": "PICCANTE (with red peppers) 1,2 lbs",
        "piecesPerCase": 6,
        "netLb": 7.5,
        "grossLb": 8.0,
        "palletTiHi": "12 x 8",
        "casesPerPallet": 96,
        "shelfDays": 240,
        "pickupLb": 6.13,
        "deliveryLb": 6.43
      },
      {
        "code": "20161",
        "packing": "BLACK PEPPER (with black peppers) 1,2 lbs",
        "piecesPerCase": 6,
        "netLb": 7.5,
        "grossLb": 8.0,
        "palletTiHi": "12 x 8",
        "casesPerPallet": 96,
        "shelfDays": 240,
        "pickupLb": 6.2,
        "deliveryLb": 6.5
      },
      {
        "code": "20229",
        "packing": "HERBS (with aromatic herbs)\n- 1,2 lbs",
        "piecesPerCase": 6,
        "netLb": 7.5,
        "grossLb": 8.0,
        "palletTiHi": "12 x 8",
        "casesPerPallet": 96,
        "shelfDays": 240,
        "pickupLb": 6.25,
        "deliveryLb": 6.55
      },
      {
        "code": "20162",
        "packing": "BLACK TRUFFLE (with black summer truffle) 1,2 lbs\npeppers) 1,2 lb",
        "piecesPerCase": 6,
        "netLb": 7.5,
        "grossLb": 8.0,
        "palletTiHi": "12 x 8",
        "casesPerPallet": 96,
        "shelfDays": 240,
        "pickupLb": 7.94,
        "deliveryLb": 8.24
      }
    ]
  },
  {
    "id": "imbriago-drunken-cheese",
    "name": "Imbriago (Drunken) Cheese",
    "range": "Alpine & Specialty",
    "price": 7.7,
    "priceMax": 7.7,
    "delivered": 8.0,
    "deliveredMax": 8.0,
    "unit": "lb",
    "multi": false,
    "image": "04028",
    "caseLb": 4.4,
    "caseLabel": "Whole Wheels vacuum packed\n- 4,4 lb",
    "wholesale": 7.7,
    "weight": "1 format · 4.4 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #009640)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "04028",
        "packing": "Whole Wheels vacuum packed\n- 4,4 lb",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 7.7,
        "deliveryLb": 8.0
      }
    ]
  },
  {
    "id": "fioretto-stagionato-small-wheel",
    "name": "Fioretto Stagionato Small Wheel",
    "range": "Fioretto",
    "price": 6.93,
    "priceMax": 6.93,
    "delivered": 7.23,
    "deliveredMax": 7.23,
    "unit": "lb",
    "multi": false,
    "image": "20313",
    "caseLb": 4.4,
    "caseLabel": "Whole Wheels vacuum packed\n- 4,4 lb",
    "wholesale": 6.93,
    "weight": "1 format · 4.4 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #141413)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20313",
        "packing": "Whole Wheels vacuum packed\n- 4,4 lb",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 6.93,
        "deliveryLb": 7.23
      }
    ]
  },
  {
    "id": "fioretto-stagionato-with-truffle",
    "name": "Fioretto Stagionato with Truffle",
    "range": "Fioretto",
    "price": 9.02,
    "priceMax": 9.02,
    "delivered": 9.32,
    "deliveredMax": 9.32,
    "unit": "lb",
    "multi": false,
    "image": "20533",
    "caseLb": 4.4,
    "caseLabel": "Whole Wheels vacuum packed\n- 4,4 lb",
    "wholesale": 9.02,
    "weight": "1 format · 4.4 lb/case",
    "grad": "linear-gradient(145deg, #064E22, #141413)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20533",
        "packing": "Whole Wheels vacuum packed\n- 4,4 lb",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 9.02,
        "deliveryLb": 9.32
      }
    ]
  },
  {
    "id": "sharp-provolone",
    "name": "Sharp Provolone",
    "range": "Provolone",
    "price": 6.46,
    "priceMax": 7.85,
    "delivered": 6.76,
    "deliveredMax": 8.15,
    "unit": "lb",
    "multi": true,
    "image": "01269",
    "caseLb": 20.0,
    "caseLabel": "Cylinder with rope, 10 lbs",
    "wholesale": 6.46,
    "weight": "4 formats · 6–40 lb/case",
    "grad": "linear-gradient(145deg, #FFFBDC, #064E22)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": true,
    "formats": [
      {
        "code": "01269",
        "packing": "Cylinder with rope, 10 lbs",
        "piecesPerCase": 2,
        "netLb": 20.0,
        "grossLb": 21.0,
        "palletTiHi": "5 x 10",
        "casesPerPallet": 50,
        "shelfDays": 240,
        "pickupLb": 6.46,
        "deliveryLb": 6.76
      },
      {
        "code": "01032",
        "packing": "Half Cylinder,\nvacuum packed, 18 - 20 lbs",
        "piecesPerCase": 2,
        "netLb": 20.0,
        "grossLb": 21.0,
        "palletTiHi": "5 x 10",
        "casesPerPallet": 50,
        "shelfDays": 240,
        "pickupLb": 6.53,
        "deliveryLb": 6.83
      },
      {
        "code": "01154",
        "packing": "Mild provolone fiaschetto rope, approx 3 lbs",
        "piecesPerCase": 2,
        "netLb": 6.0,
        "grossLb": 7.5,
        "palletTiHi": "24 x 10",
        "casesPerPallet": 240,
        "shelfDays": 240,
        "pickupLb": 6.93,
        "deliveryLb": 7.23
      },
      {
        "code": "01126",
        "packing": "round shape with rope aged minimum 5 months",
        "piecesPerCase": 1,
        "netLb": 40.0,
        "grossLb": 42.0,
        "palletTiHi": "6 x 5",
        "casesPerPallet": 30,
        "shelfDays": 240,
        "pickupLb": 7.85,
        "deliveryLb": 8.15
      }
    ]
  },
  {
    "id": "mild-provolone",
    "name": "Mild Provolone",
    "range": "Provolone",
    "price": 6.09,
    "priceMax": 6.09,
    "delivered": 6.39,
    "deliveredMax": 6.39,
    "unit": "lb",
    "multi": false,
    "image": "20438",
    "caseLb": 14.0,
    "caseLabel": "Cylinder, vacuum packed, 7 lbs approx",
    "wholesale": 6.09,
    "weight": "1 format · 14 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #064E22)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20438",
        "packing": "Cylinder, vacuum packed, 7 lbs approx",
        "piecesPerCase": 2,
        "netLb": 14.0,
        "grossLb": 15.0,
        "palletTiHi": "6 x 12",
        "casesPerPallet": 72,
        "shelfDays": 240,
        "pickupLb": 6.09,
        "deliveryLb": 6.39
      }
    ]
  },
  {
    "id": "naturally-smoked-provolone",
    "name": "Naturally Smoked Provolone",
    "range": "Provolone",
    "price": 6.21,
    "priceMax": 7.38,
    "delivered": 6.51,
    "deliveredMax": 7.68,
    "unit": "lb",
    "multi": true,
    "image": "01021",
    "caseLb": 15.5,
    "caseLabel": "Pan di Cacio - Round bread format 7,7 lb",
    "wholesale": 6.21,
    "weight": "3 formats · 6–15.5 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #064E22)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "01021",
        "packing": "Pan di Cacio - Round bread format 7,7 lb",
        "piecesPerCase": 2,
        "netLb": 15.5,
        "grossLb": 16.5,
        "palletTiHi": "6 x 12",
        "casesPerPallet": 72,
        "shelfDays": 240,
        "pickupLb": 6.45,
        "deliveryLb": 6.75
      },
      {
        "code": "01186",
        "packing": "Cylinder, vacuum packed, 7 lbs approx",
        "piecesPerCase": 2,
        "netLb": 14.0,
        "grossLb": 15.0,
        "palletTiHi": "6 x 12",
        "casesPerPallet": 72,
        "shelfDays": 240,
        "pickupLb": 6.21,
        "deliveryLb": 6.51
      },
      {
        "code": "01155",
        "packing": "Smoked  provolone fiaschetto rope, approx 3 lbs",
        "piecesPerCase": 2,
        "netLb": 6.0,
        "grossLb": 7.5,
        "palletTiHi": "12 x 8",
        "casesPerPallet": 96,
        "shelfDays": 240,
        "pickupLb": 7.38,
        "deliveryLb": 7.68
      }
    ]
  },
  {
    "id": "alta-badia-cheese",
    "name": "Alta Badia Cheese",
    "range": "Alpine & Specialty",
    "price": 11.61,
    "priceMax": 11.61,
    "delivered": 11.91,
    "deliveredMax": 11.91,
    "unit": "lb",
    "multi": false,
    "image": "20464",
    "caseLb": 18.0,
    "caseLabel": "Whole Wheels approx 18 lbs vacuum packed",
    "wholesale": 11.61,
    "weight": "1 format · 18 lb/case",
    "grad": "linear-gradient(145deg, #E3F0E1, #009640)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20464",
        "packing": "Whole Wheels approx 18 lbs vacuum packed",
        "piecesPerCase": 1,
        "netLb": 18.0,
        "grossLb": 20.02,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 11.61,
        "deliveryLb": 11.91
      }
    ]
  },
  {
    "id": "stelvio-cheese-dop",
    "name": "Stelvio Cheese DOP",
    "range": "Alpine & Specialty",
    "price": 9.5,
    "priceMax": 9.5,
    "delivered": 9.8,
    "deliveredMax": 9.8,
    "unit": "lb",
    "multi": false,
    "image": "20584",
    "caseLb": 18.0,
    "caseLabel": "Whole Wheels approx 18 lbs vacuum packed",
    "wholesale": 9.5,
    "weight": "1 format · 18 lb/case",
    "grad": "linear-gradient(145deg, #FFFBDC, #70C883)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20584",
        "packing": "Whole Wheels approx 18 lbs vacuum packed",
        "piecesPerCase": 1,
        "netLb": 18.0,
        "grossLb": 20.02,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 9.5,
        "deliveryLb": 9.8
      }
    ]
  },
  {
    "id": "piave-cheese-dop",
    "name": "Piave Cheese DOP",
    "range": "Alpine & Specialty",
    "price": 8.29,
    "priceMax": 9.75,
    "delivered": 8.59,
    "deliveredMax": 10.05,
    "unit": "lb",
    "multi": true,
    "image": "40107",
    "caseLb": 13.0,
    "caseLabel": "MEZZANO Whole Wheels approx 13 lbs vacuum packed",
    "wholesale": 8.29,
    "weight": "3 formats · 11–13 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #009640)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "40107",
        "packing": "MEZZANO Whole Wheels approx 13 lbs vacuum packed",
        "piecesPerCase": 1,
        "netLb": 13.0,
        "grossLb": 14.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 360,
        "pickupLb": 8.29,
        "deliveryLb": 8.59
      },
      {
        "code": "40109",
        "packing": "AGED MORE THAN 6 months Whole Wheels approx 12 lbs vacuum packed",
        "piecesPerCase": 1,
        "netLb": 12.0,
        "grossLb": 13.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 360,
        "pickupLb": 8.65,
        "deliveryLb": 8.95
      },
      {
        "code": "40158",
        "packing": "AGED MORE THAN 12 MONTHS\nWhole Wheels approx 11 lbs vacuum packed",
        "piecesPerCase": 1,
        "netLb": 11.0,
        "grossLb": 12.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 360,
        "pickupLb": 9.75,
        "deliveryLb": 10.05
      }
    ]
  },
  {
    "id": "gorgonzola-dop-mild",
    "name": "Gorgonzola DOP Mild",
    "range": "Alpine & Specialty",
    "price": 6.81,
    "priceMax": 6.81,
    "delivered": 7.11,
    "deliveredMax": 7.11,
    "unit": "lb",
    "multi": false,
    "image": "20519",
    "caseLb": 4.0,
    "caseLabel": "1/8 Wheels approx 4 lbs vacuum packed",
    "wholesale": 6.81,
    "weight": "1 format · 4 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #141413)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20519",
        "packing": "1/8 Wheels approx 4 lbs vacuum packed",
        "piecesPerCase": 1,
        "netLb": 4.0,
        "grossLb": 4.4,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 90,
        "pickupLb": 6.81,
        "deliveryLb": 7.11
      }
    ]
  },
  {
    "id": "taleggio-dop",
    "name": "Taleggio DOP",
    "range": "Alpine & Specialty",
    "price": 6.95,
    "priceMax": 6.95,
    "delivered": 7.25,
    "deliveredMax": 7.25,
    "unit": "lb",
    "multi": false,
    "image": "20520",
    "caseLb": 4.0,
    "caseLabel": "Whole Wheels approx 4,4 lbs vacuum packed",
    "wholesale": 6.95,
    "weight": "1 format · 4 lb/case",
    "grad": "linear-gradient(145deg, #064E22, #141413)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20520",
        "packing": "Whole Wheels approx 4,4 lbs vacuum packed",
        "piecesPerCase": 1,
        "netLb": 4.0,
        "grossLb": 5.0,
        "palletTiHi": "7 x 10",
        "casesPerPallet": 70,
        "shelfDays": 70,
        "pickupLb": 6.95,
        "deliveryLb": 7.25
      }
    ]
  },
  {
    "id": "grana-padano",
    "name": "Grana Padano",
    "range": "Grana Padano",
    "price": 7.47,
    "priceMax": 7.68,
    "delivered": 7.77,
    "deliveredMax": 7.98,
    "unit": "lb",
    "multi": true,
    "image": "05001",
    "caseLb": 72.0,
    "caseLabel": "Whole Wheel, 66-77 lbs",
    "wholesale": 7.47,
    "weight": "3 formats · 18–72 lb/case",
    "grad": "linear-gradient(145deg, #FFFBDC, #064E22)",
    "badge": "Mountain",
    "blurb": "Aged min. 12–16 months. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged min. 12–16 months",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": true,
    "formats": [
      {
        "code": "05001",
        "packing": "Whole Wheel, 66-77 lbs",
        "piecesPerCase": 1,
        "netLb": 72.0,
        "grossLb": 72.0,
        "palletTiHi": "6 x 5",
        "casesPerPallet": 30,
        "shelfDays": 360,
        "pickupLb": 7.47,
        "deliveryLb": 7.77
      },
      {
        "code": "05007",
        "packing": "1/8 Wheel, vacuum packed",
        "piecesPerCase": 2,
        "netLb": 18.0,
        "grossLb": 19.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 7.68,
        "deliveryLb": 7.98
      },
      {
        "code": "05012",
        "packing": "1/2 horizontal cut for party",
        "piecesPerCase": 1,
        "netLb": 36.0,
        "grossLb": 37.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 7.63,
        "deliveryLb": 7.93
      }
    ]
  },
  {
    "id": "grana-padano-riserva",
    "name": "Grana Padano Riserva",
    "range": "Grana Padano",
    "price": 8.47,
    "priceMax": 10.13,
    "delivered": 8.77,
    "deliveredMax": 10.43,
    "unit": "lb",
    "multi": true,
    "image": "05093",
    "caseLb": 72.0,
    "caseLabel": "Whole Wheel, 66-77 lbs",
    "wholesale": 8.47,
    "weight": "4 formats · 18–72 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #064E22)",
    "badge": "Mountain",
    "blurb": "Aged min. 16–20 months. Mountain milk from the Trentino Alps, made and aged in our own plants in Grigno.",
    "age": "aged min. 16–20 months",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "05093",
        "packing": "Whole Wheel, 66-77 lbs",
        "piecesPerCase": 1,
        "netLb": 72.0,
        "grossLb": 72.0,
        "palletTiHi": "6 x 5",
        "casesPerPallet": 30,
        "shelfDays": 360,
        "pickupLb": 8.47,
        "deliveryLb": 8.77
      },
      {
        "code": "05018",
        "packing": "1/8 Wheel, vacuum packed minimum\n16 months ageing",
        "piecesPerCase": 2,
        "netLb": 18.0,
        "grossLb": 19.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 8.8,
        "deliveryLb": 9.1
      },
      {
        "code": "05411",
        "packing": "RISERVA AGED MIN. 20 MONTHS\nWhole Wheel, 66-77 lbs",
        "piecesPerCase": 1,
        "netLb": 72.0,
        "grossLb": 72.0,
        "palletTiHi": "6 x 5",
        "casesPerPallet": 30,
        "shelfDays": 360,
        "pickupLb": 9.48,
        "deliveryLb": 9.78
      },
      {
        "code": "05095",
        "packing": "TRENTIN GRANA                     AGED MIN. 20 MONTHS          Whole\nWheel, 66-77 lbs",
        "piecesPerCase": 1,
        "netLb": 72.0,
        "grossLb": 72.0,
        "palletTiHi": "6 x 5",
        "casesPerPallet": 30,
        "shelfDays": 360,
        "pickupLb": 10.13,
        "deliveryLb": 10.43
      }
    ]
  },
  {
    "id": "parmigiano-reggiano-pdo",
    "name": "Parmigiano Reggiano PDO",
    "range": "Parmigiano",
    "price": 11.64,
    "priceMax": 13.96,
    "delivered": 11.94,
    "deliveredMax": 14.26,
    "unit": "lb",
    "multi": true,
    "image": "05034",
    "caseLb": 72.0,
    "caseLabel": "Aged minimum 12 months\nWhole Wheel, 66-77 lbs",
    "wholesale": 11.64,
    "weight": "3 formats · 18–72 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #064E22)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": true,
    "formats": [
      {
        "code": "05034",
        "packing": "Aged minimum 12 months\nWhole Wheel, 66-77 lbs",
        "piecesPerCase": 1,
        "netLb": 72.0,
        "grossLb": 72.0,
        "palletTiHi": "6 x 5",
        "casesPerPallet": 30,
        "shelfDays": 360,
        "pickupLb": 11.64,
        "deliveryLb": 11.94
      },
      {
        "code": "05025",
        "packing": "Aged minimum 12 months 1/8 Wheel, vacuum packed",
        "piecesPerCase": 2,
        "netLb": 18.0,
        "grossLb": 19.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 60,
        "shelfDays": 240,
        "pickupLb": 11.78,
        "deliveryLb": 12.08
      },
      {
        "code": "05033",
        "packing": "Aged minimum 24 months\nWhole Wheel, 66-77 lbs",
        "piecesPerCase": 1,
        "netLb": 72.0,
        "grossLb": 72.0,
        "palletTiHi": "6 x 5",
        "casesPerPallet": 30,
        "shelfDays": 360,
        "pickupLb": 13.96,
        "deliveryLb": 14.26
      }
    ]
  },
  {
    "id": "pecorino-romano-dop",
    "name": "Pecorino Romano DOP",
    "range": "Pecorino & Sheep",
    "price": 7.49,
    "priceMax": 7.68,
    "delivered": 7.79,
    "deliveredMax": 7.98,
    "unit": "lb",
    "multi": true,
    "image": "40103",
    "caseLb": 58.0,
    "caseLabel": "Whole Wheels vacuum packed\n- 58 lbS Approx",
    "wholesale": 7.49,
    "weight": "2 formats · 58 lb/case",
    "grad": "linear-gradient(145deg, #E3F0E1, #009640)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "40103",
        "packing": "Whole Wheels vacuum packed\n- 58 lbS Approx",
        "piecesPerCase": 1,
        "netLb": 58.0,
        "grossLb": 59.0,
        "palletTiHi": "9 x 5",
        "casesPerPallet": 45,
        "shelfDays": 360,
        "pickupLb": 7.49,
        "deliveryLb": 7.79
      },
      {
        "code": "40104",
        "packing": "1/4 Wheel, vacuum packed",
        "piecesPerCase": 4,
        "netLb": 58.0,
        "grossLb": 59.0,
        "palletTiHi": "9 x 5",
        "casesPerPallet": 45,
        "shelfDays": 360,
        "pickupLb": 7.68,
        "deliveryLb": 7.98
      }
    ]
  },
  {
    "id": "pecorino-toscano-dop",
    "name": "Pecorino Toscano DOP",
    "range": "Pecorino & Sheep",
    "price": 9.19,
    "priceMax": 10.02,
    "delivered": 9.49,
    "deliveredMax": 10.32,
    "unit": "lb",
    "multi": true,
    "image": "40174",
    "caseLb": 12.0,
    "caseLabel": "Whole Wheels Aged minimum 60 days\n- 6 lbS Approx vacuum packed",
    "wholesale": 9.19,
    "weight": "2 formats · 12 lb/case",
    "grad": "linear-gradient(145deg, #FFFBDC, #70C883)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "40174",
        "packing": "Whole Wheels Aged minimum 60 days\n- 6 lbS Approx vacuum packed",
        "piecesPerCase": 2,
        "netLb": 12.0,
        "grossLb": 13.0,
        "palletTiHi": "6 x 14",
        "casesPerPallet": 84,
        "shelfDays": 240,
        "pickupLb": 9.19,
        "deliveryLb": 9.49
      },
      {
        "code": "40175",
        "packing": "Whole wheel Aged minimum 120 days\n- 6 lbS Approx vacuum packed",
        "piecesPerCase": 2,
        "netLb": 12.0,
        "grossLb": 13.0,
        "palletTiHi": "6 x 14",
        "casesPerPallet": 84,
        "shelfDays": 240,
        "pickupLb": 10.02,
        "deliveryLb": 10.32
      }
    ]
  },
  {
    "id": "ricotta-salata-saporita",
    "name": "Ricotta Salata Saporita",
    "range": "Pecorino & Sheep",
    "price": 4.2,
    "priceMax": 4.2,
    "delivered": 4.5,
    "deliveredMax": 4.5,
    "unit": "lb",
    "multi": false,
    "image": "40140",
    "caseLb": 14.0,
    "caseLabel": "Whole Wheels approx 7 lbs vacuum packed",
    "wholesale": 4.2,
    "weight": "1 format · 14 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #009640)",
    "badge": "Mountain",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "40140",
        "packing": "Whole Wheels approx 7 lbs vacuum packed",
        "piecesPerCase": 2,
        "netLb": 14.0,
        "grossLb": 15.0,
        "palletTiHi": "6 x 10",
        "casesPerPallet": 96,
        "shelfDays": 240,
        "pickupLb": 4.2,
        "deliveryLb": 4.5
      }
    ]
  },
  {
    "id": "pecorino-siciliano-primosale",
    "name": "Pecorino Siciliano Primosale",
    "range": "Pecorino & Sheep",
    "price": 7.75,
    "priceMax": 11.62,
    "delivered": 8.05,
    "deliveredMax": 11.92,
    "unit": "lb",
    "multi": true,
    "image": "20700",
    "caseLb": 10.0,
    "caseLabel": "Pecorino white Whole Wheels approx 14 oz lbs vacuum packed",
    "wholesale": 7.75,
    "weight": "6 formats · 10 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #141413)",
    "badge": "Pre-order",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "preorder",
    "featured": false,
    "formats": [
      {
        "code": "20700",
        "packing": "Pecorino white Whole Wheels approx 14 oz lbs vacuum packed",
        "piecesPerCase": 9,
        "netLb": 10.0,
        "grossLb": 11.0,
        "palletTiHi": "8 x 8",
        "casesPerPallet": 64,
        "shelfDays": 120,
        "pickupLb": 7.75,
        "deliveryLb": 8.05
      },
      {
        "code": "20701",
        "packing": "pecorino with olives Whole Wheels approx 14 oz lbs vacuum packed",
        "piecesPerCase": 9,
        "netLb": 10.0,
        "grossLb": 11.0,
        "palletTiHi": "8 x 8",
        "casesPerPallet": 64,
        "shelfDays": 120,
        "pickupLb": 8.02,
        "deliveryLb": 8.32
      },
      {
        "code": "20702",
        "packing": "Pecorino with curry Whole Wheels approx 14 oz lbs vacuum packed",
        "piecesPerCase": 9,
        "netLb": 10.0,
        "grossLb": 11.0,
        "palletTiHi": "8 x 8",
        "casesPerPallet": 64,
        "shelfDays": 120,
        "pickupLb": 8.1,
        "deliveryLb": 8.4
      },
      {
        "code": "20703",
        "packing": "pecorino ghiotto with Whole Wheels approx 14 oz lbs vacuum packed",
        "piecesPerCase": 9,
        "netLb": 10.0,
        "grossLb": 11.0,
        "palletTiHi": "8 x 8",
        "casesPerPallet": 64,
        "shelfDays": 120,
        "pickupLb": 8.18,
        "deliveryLb": 8.48
      },
      {
        "code": "20719",
        "packing": "Pecorino saffron & bacck pepper Whole Wheels approx 14 oz lbs vacuum packed",
        "piecesPerCase": 9,
        "netLb": 10.0,
        "grossLb": 11.0,
        "palletTiHi": "8 x 8",
        "casesPerPallet": 64,
        "shelfDays": 120,
        "pickupLb": 11.62,
        "deliveryLb": 11.92
      },
      {
        "code": "20720",
        "packing": "Pecorino with pistachio Whole Wheels approx 14 oz lbs vacuum packed",
        "piecesPerCase": 9,
        "netLb": 10.0,
        "grossLb": 11.0,
        "palletTiHi": "8 x 8",
        "casesPerPallet": 64,
        "shelfDays": 120,
        "pickupLb": 8.33,
        "deliveryLb": 8.63
      }
    ]
  },
  {
    "id": "toma-piemontese-dop",
    "name": "Toma Piemontese DOP",
    "range": "Piemontesi",
    "price": 8.26,
    "priceMax": 8.26,
    "delivered": 8.56,
    "deliveredMax": 8.56,
    "unit": "lb",
    "multi": false,
    "image": "20452",
    "caseLb": 4.4,
    "caseLabel": "TOMA Whole Wheels vacuum packed - 15 lbS Approx",
    "wholesale": 8.26,
    "weight": "1 format · 4.4 lb/case",
    "grad": "linear-gradient(145deg, #064E22, #141413)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20452",
        "packing": "TOMA Whole Wheels vacuum packed - 15 lbS Approx",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 180,
        "pickupLb": 8.26,
        "deliveryLb": 8.56
      }
    ]
  },
  {
    "id": "bra-piemontese-dop",
    "name": "Bra Piemontese DOP",
    "range": "Piemontesi",
    "price": 8.26,
    "priceMax": 9.94,
    "delivered": 8.56,
    "deliveredMax": 10.24,
    "unit": "lb",
    "multi": true,
    "image": "20450",
    "caseLb": 4.4,
    "caseLabel": "TENERO/SOFT -Whole Wheels vacuum packed\n- 15 lbS Approx",
    "wholesale": 8.26,
    "weight": "2 formats · 3.5–4.4 lb/case",
    "grad": "linear-gradient(145deg, #FFFBDC, #064E22)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20450",
        "packing": "TENERO/SOFT -Whole Wheels vacuum packed\n- 15 lbS Approx",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 180,
        "pickupLb": 8.26,
        "deliveryLb": 8.56
      },
      {
        "code": "20451",
        "packing": "DURO/HARD Whole Wheels vacuum packed\n- 15 lbS Approx",
        "piecesPerCase": 1,
        "netLb": 3.5,
        "grossLb": 4.0,
        "palletTiHi": "25x10",
        "casesPerPallet": 250,
        "shelfDays": 180,
        "pickupLb": 9.94,
        "deliveryLb": 10.24
      }
    ]
  },
  {
    "id": "raschera-piemontese-dop",
    "name": "Raschera Piemontese DOP",
    "range": "Piemontesi",
    "price": 8.09,
    "priceMax": 8.09,
    "delivered": 8.39,
    "deliveredMax": 8.39,
    "unit": "lb",
    "multi": false,
    "image": "20453",
    "caseLb": 4.4,
    "caseLabel": "TENERO/SOFT -Whole Wheels vacuum packed\n- 15 lbS Approx",
    "wholesale": 8.09,
    "weight": "1 format · 4.4 lb/case",
    "grad": "linear-gradient(145deg, #C8E2C5, #064E22)",
    "badge": "PDO",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "in_stock",
    "featured": false,
    "formats": [
      {
        "code": "20453",
        "packing": "TENERO/SOFT -Whole Wheels vacuum packed\n- 15 lbS Approx",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 180,
        "pickupLb": 8.09,
        "deliveryLb": 8.39
      }
    ]
  },
  {
    "id": "castelmagno-dop",
    "name": "Castelmagno DOP",
    "range": "Piemontesi",
    "price": 20.08,
    "priceMax": 20.08,
    "delivered": 20.38,
    "deliveredMax": 20.38,
    "unit": "lb",
    "multi": false,
    "image": "20567",
    "caseLb": 4.4,
    "caseLabel": "Whole Wheels vacuum packed\n- 15 lbS Approx",
    "wholesale": 20.08,
    "weight": "1 format · 4.4 lb/case",
    "grad": "linear-gradient(145deg, #70C883, #064E22)",
    "badge": "Limited",
    "blurb": "From the Trentino mountains — made and aged in our own plants in Grigno.",
    "age": "—",
    "milk": "Mountain milk",
    "availability": "unavailable",
    "featured": false,
    "formats": [
      {
        "code": "20567",
        "packing": "Whole Wheels vacuum packed\n- 15 lbS Approx",
        "piecesPerCase": 1,
        "netLb": 4.4,
        "grossLb": 5.0,
        "palletTiHi": "24 x 8",
        "casesPerPallet": 192,
        "shelfDays": 240,
        "pickupLb": 20.08,
        "deliveryLb": 20.38
      }
    ]
  }
];
  if (window.STORE_DATA) { window.STORE_DATA.products = products; }
  else { window.STORE_DATA = { products, recipes: [], posts: [], social: [], HERO: "" }; }
  window.TRADE_CATALOG = products;
})();
